//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP_EMS_SP.DevelopWP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APPLICATION_COMPANY_CORE_MEMBER
    {
        public int Core_Member_ID { get; set; }
        public System.Guid Application_ID { get; set; }
        public int Programme_ID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string HKID { get; set; }
        public string Background_Information { get; set; }
        public string Bootcamp_Eligible_Number { get; set; }
        public string Professional_Qualifications { get; set; }
        public string Working_Experiences { get; set; }
        public string Special_Achievements { get; set; }
        public string CoreMember_Profile { get; set; }
        public string Masked_HKID { get; set; }
    }
}
