//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP_EMS_SP.DevelopWP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CCMF_APPLICATION
    {
        public System.Guid CCMF_ID_ { get; set; }
        public int Programme_ID { get; set; }
        public string Application_Number { get; set; }
        public int Intake_Number { get; set; }
        public string Applicant { get; set; }
        public System.DateTime Last_Submitted { get; set; }
        public string Status { get; set; }
        public string Version_Number { get; set; }
        public string Programme_Type { get; set; }
        public string Hong_Kong_Programme_Stream { get; set; }
        public string CrossBorder_Programme_Type { get; set; }
        public string CCMF_Application_Type { get; set; }
        public Nullable<bool> Question2_1_1a { get; set; }
        public Nullable<bool> Question2_1_1b { get; set; }
        public Nullable<bool> Question2_1_1c { get; set; }
        public Nullable<bool> Question2_1_1d { get; set; }
        public Nullable<bool> Question2_1_1e { get; set; }
        public Nullable<bool> Question2_1_1f { get; set; }
        public Nullable<bool> Question2_1_1g { get; set; }
        public Nullable<bool> Question2_1_1h { get; set; }
        public Nullable<bool> Question2_1_1i { get; set; }
        public Nullable<bool> Question2_1_1j { get; set; }
        public Nullable<bool> Question2_1_2a { get; set; }
        public Nullable<bool> Question2_1_2b { get; set; }
        public Nullable<bool> Question2_1_2c { get; set; }
        public Nullable<bool> Question2_1_2d { get; set; }
        public Nullable<bool> Question2_1_2e { get; set; }
        public Nullable<bool> Question2_1_2f { get; set; }
        public Nullable<bool> Question2_1_2g { get; set; }
        public Nullable<bool> Question2_1_2h { get; set; }
        public Nullable<bool> Question2_1_2i { get; set; }
        public Nullable<bool> Question2_1_2j { get; set; }
        public Nullable<bool> Question2_1_2k { get; set; }
        public Nullable<bool> Question2_2a { get; set; }
        public Nullable<bool> Question2_2b { get; set; }
        public Nullable<bool> Question2_2c { get; set; }
        public Nullable<bool> Question2_2d { get; set; }
        public Nullable<bool> Question2_2e { get; set; }
        public Nullable<bool> Question2_2f { get; set; }
        public Nullable<bool> Question2_2g { get; set; }
        public Nullable<bool> Question2_2h { get; set; }
        public Nullable<bool> Question2_2i { get; set; }
        public Nullable<bool> Question2_2j { get; set; }
        public Nullable<bool> Question2_2k { get; set; }
        public Nullable<bool> Question2_2l { get; set; }
        public Nullable<bool> Question2_2m { get; set; }
        public Nullable<bool> Question2_3_1a { get; set; }
        public Nullable<bool> Question2_3_1b { get; set; }
        public Nullable<bool> Question2_3_1c { get; set; }
        public Nullable<bool> Question2_3_1d { get; set; }
        public Nullable<bool> Question2_3_1e { get; set; }
        public Nullable<bool> Question2_3_1f { get; set; }
        public Nullable<bool> Question2_3_1g { get; set; }
        public Nullable<bool> Question2_3_1h { get; set; }
        public Nullable<bool> Question2_3_1i { get; set; }
        public Nullable<bool> Question2_3_1j { get; set; }
        public Nullable<bool> Question2_3_1k { get; set; }
        public string Project_Name_Eng { get; set; }
        public string Project_Name_Chi { get; set; }
        public string Abstract_Eng { get; set; }
        public string Abstract_Chi { get; set; }
        public string Business_Area { get; set; }
        public string Other_Business_Area { get; set; }
        public Nullable<System.DateTime> Commencement_Date { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public Nullable<bool> Declaration { get; set; }
        public Nullable<bool> Have_Read_Statement { get; set; }
        public Nullable<bool> Marketing_Information { get; set; }
        public string Principal_Full_Name { get; set; }
        public string Principal_Position_Title { get; set; }
        public Nullable<System.DateTime> Submission_Date { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Project_Management_Team { get; set; }
        public string Business_Model { get; set; }
        public string Innovation { get; set; }
        public string Social_Responsibility { get; set; }
        public string Competition_Analysis { get; set; }
        public string Project_Milestone_M1 { get; set; }
        public string Project_Milestone_M2 { get; set; }
        public string Project_Milestone_M3 { get; set; }
        public string Project_Milestone_M4 { get; set; }
        public string Project_Milestone_M5 { get; set; }
        public string Project_Milestone_M6 { get; set; }
        public string Cost_Projection { get; set; }
        public string Exit_Stategy { get; set; }
        public string Additional_Information { get; set; }
        public string Application_Parent_ID { get; set; }
        public string Advisor_Info { get; set; }
    }
}
