//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP_EMS_SP.DevelopWP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROGRAMME_INTAKE
    {
        public int Programme_ID { get; set; }
        public string Programme_Name { get; set; }
        public int Intake_Number { get; set; }
        public string Application_No_Prefix { get; set; }
        public System.DateTime Application_Start { get; set; }
        public System.DateTime Application_Deadline { get; set; }
        public string Application_Deadline_Eng { get; set; }
        public string Application_Deadline_TradChin { get; set; }
        public string Application_Deadline_SimpChin { get; set; }
        public string Vetting_Session_Eng { get; set; }
        public string Vetting_Session_TradChin { get; set; }
        public string Vetting_Session_SimpChin { get; set; }
        public string Result_Announce_Eng { get; set; }
        public string Result_Announce_TradChin { get; set; }
        public string Result_Announce_Simp_Chin { get; set; }
        public bool Active { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
    }
}
