//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP_EMS_SP.DevelopWP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RESET_PASSWORD
    {
        public System.Guid Reset_Password_ID { get; set; }
        public string Email { get; set; }
        public string Email_Type { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
