//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP_EMS_SP.DevelopWP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SCREENING_HISTORY
    {
        public int Screening_Comments_ID { get; set; }
        public string Application_Number { get; set; }
        public int Programme_ID { get; set; }
        public string Validation_Result { get; set; }
        public string Comment_For_Applicants { get; set; }
        public string Comment_For_Internal_Use { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
