
CREATE TABLE [dbo].[TB_INCUBATION_APPLICATION_HISTORY](
	[Incubation_ID ] [uniqueidentifier] NOT NULL,
	[Programme_ID] [int] NOT NULL,
	[Application_Number] [nvarchar](50) NOT NULL,
	[Intake_Number] [int] NOT NULL,
	[Applicant] [nvarchar](255) NOT NULL,
	[Last_Submitted] [datetime] NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[Version_Number] [nvarchar](20) NOT NULL,
	[Question1_1] [bit] NULL,
	[Question1_2] [bit] NULL,
	[Question1_3] [bit] NULL,
	[Question1_4] [bit] NULL,
	[Question1_5] [bit] NULL,
	[Question1_6] [bit] NULL,
	[Question1_7] [bit] NULL,
	[Question1_8] [bit] NULL,
	[Question1_9] [bit] NULL,
	[Question1_10] [bit] NULL,
	[Company_Name_Eng] [nvarchar](255) NULL,
	[Company_Name_Chi] [nvarchar](255) NULL,
	[Abstract] [ntext] NULL,
	[Objective] [ntext] NULL,
	[Background] [ntext] NULL,
	[Pilot_Work_Done] [ntext] NULL,
	[Additional_Information] [ntext] NULL,
	[Proposed_Products] [ntext] NULL,
	[Target_Market] [ntext] NULL,
	[Competition_Analysis] [ntext] NULL,
	[Revenus_Model] [ntext] NULL,
	[Exit_Strategy] [ntext] NULL,
	[First_6_Months_Milestone] [nvarchar](max) NULL,
	[Second_6_Months_Milestone] [nvarchar](max) NULL,
	[Third_6_Months_Milestone] [nvarchar](max) NULL,
	[Forth_6_Months_Milestone] [nvarchar](max) NULL,
	[Resubmission] [bit] NULL,
	[Resubmission_Project_Reference] [ntext] NULL,
	[Resubmission_Main_Differences] [ntext] NULL,
	[Company_Type] [nchar](10) NULL,
	[Other_Company_Type] [nvarchar](255) NULL,
	[Business_Area] [nvarchar](30) NULL,
	[Other_Bussiness_Area] [nvarchar](30) NULL,
	[Positioning] [ntext] NULL,
	[Management_Positioning] [nvarchar](255) NULL,
	[Other_Positioning] [nvarchar](255) NULL,
	[Other_Attributes] [ntext] NULL,
	[Preferred_Track] [nvarchar](30) NULL,
	[Company_Ownership_Structure] [ntext] NULL,
	[Core_Members_Profiles] [ntext] NULL,
	[Major_Partners_Profiles] [ntext] NULL,
	[Manpower_Distribution] [ntext] NULL,
	[Equipment_Distribution] [ntext] NULL,
	[Other_Direct_Costs] [ntext] NULL,
	[Forecast_Income] [ntext] NULL,
	[Declaration] [bit] NULL,
	[Have_Read_Statement] [bit] NULL,
	[Marketing_Information] [bit] NULL,
	[Principal_Full_Name] [nvarchar](255) NULL,
	[Principal_Position_Title] [nvarchar](255) NULL,
	[Submission_Date] [datetime] NULL,
	[Created_By] [nvarchar](50) NOT NULL,
	[Created_Date] [datetime] NOT NULL,
	[Modified_By] [nvarchar](50) NOT NULL,
	[Modified_Date] [datetime] NOT NULL,
	[Abstract_Chi] [ntext] NULL,
	[Application_Parent_ID] [nvarchar](36) NULL
)