//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP_EMS_SP.CPIP_FA_Reimbursement_Form.VisualWebPart1 {
    using System.Web.UI.WebControls.Expressions;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using CBP_EMS_SP.Common;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.CodeDom.Compiler;
    
    
    public partial class VisualWebPart1 {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdn_FAApplicationID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lblApplicant;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lblApplicationNo;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lblLastSubmitted;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.RadioButtonList rdo_Categories;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlCompanyList;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtBankChequePayble;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlBankChequePayble;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventsAttend;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlEventsAttend;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlslct_Location;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlslct_Location;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventFrom;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventTo;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnplEventCatBC;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdReimbursementItems;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlReimbursementItems;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlReimbursementItemTotalInitialGrant;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.ImageButton btnAddReimbursementItem;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label btnReimbursementItemError;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_BankTotal;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_BankDeduct;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_BankNetAmount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlReimbursementItemTotal;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlReimbursementSalary;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTransferBankName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTransferBankCode;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTransferBankAccount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTransferBankSwift;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTransferBankAcHolderName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.CheckBox chk_RemarksInitialGrant;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.WebControls.Panel pnlDirectBankTransfer;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart1 target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdn_FAApplicationID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdn_FAApplicationID = @__ctrl;
            @__ctrl.ID = "hdn_FAApplicationID";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllblApplicant() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblApplicant = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblApplicant";
            @__ctrl.Text = "";
            @__ctrl.CssClass = "word-wrap";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllblApplicationNo() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblApplicationNo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblApplicationNo";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllblLastSubmitted() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblLastSubmitted = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblLastSubmitted";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.RadioButtonList @__BuildControlrdo_Categories() {
            global::System.Web.UI.WebControls.RadioButtonList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RadioButtonList();
            this.rdo_Categories = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.AutoPostBack = true;
            @__ctrl.CellPadding = 5;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.ID = "rdo_Categories";
            @__ctrl.RepeatDirection = global::System.Web.UI.WebControls.RepeatDirection.Horizontal;
            @__ctrl.RepeatColumns = 3;
            @__ctrl.CssClass = "listcss";
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.rdo_Categories_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.rdo_Categories_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlCompanyList() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlCompanyList = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlCompanyList";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "height: 40px");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control2() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ImageUrl = "/_layouts/15/images/CBP_Images/Intrnal%20Use-Drop%20Down.png";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "vertical-align: top");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBankChequePayble() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtBankChequePayble = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtBankChequePayble";
            @__ctrl.CssClass = "form-control input-sm-nobackground";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlBankChequePayble() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlBankChequePayble = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlBankChequePayble";
            @__ctrl.Visible = false;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "col-md-4");
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtBankChequePayble();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlBankChequePayble));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__RenderpnlBankChequePayble(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                    <p>\r\n                        <label>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_BankChequePayble", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                    </p>\r\n                    ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventsAttend() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventsAttend = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventsAttend";
            @__ctrl.CssClass = "form-control input-sm";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlEventsAttend() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlEventsAttend = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlEventsAttend";
            @__ctrl.Visible = false;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "col-md-4");
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtEventsAttend();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlEventsAttend));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__RenderpnlEventsAttend(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                    <p>\r\n                        <label>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_EventsAttend", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                    </p>\r\n                    ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlslct_Location() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlslct_Location = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlslct_Location";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "height: 40px");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control3() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ImageUrl = "/_layouts/15/images/CBP_Images/Intrnal%20Use-Drop%20Down.png";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "vertical-align: top");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlslct_Location() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlslct_Location = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlslct_Location";
            @__ctrl.Visible = false;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "col-md-4");
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlslct_Location();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Image @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Renderpnlslct_Location));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Renderpnlslct_Location(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                    <p>\r\n                        <label>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_slct_Location", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                    </p>\r\n                    ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n                ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventFrom() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventFrom = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventFrom";
            @__ctrl.CssClass = "input-sm hidedates datepickermmddyyy";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control4() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ImageUrl = "/_layouts/15/images/CBP_Images/Calender.png";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "vertical-align: top");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventTo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventTo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventTo";
            @__ctrl.CssClass = "input-sm hidedates datepickermmddyyy";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control5() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ImageUrl = "/_layouts/15/images/CBP_Images/Calender.png";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "vertical-align: top");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnplEventCatBC() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnplEventCatBC = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnplEventCatBC";
            @__ctrl.CssClass = "row";
            @__ctrl.Visible = false;
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtEventFrom();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Image @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxtEventTo();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Image @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control5();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnplEventCatBC));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__RenderpnplEventCatBC(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                <div class=\"col-md-4\">\r\n                    <p>\r\n              " +
                    "          <label>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_EventFrom", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                    </p>\r\n                    ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                <div class=\"col-md-4\">\r\n               " +
                    "     <p>\r\n                        <label>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_EventTo", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                    </p>\r\n                    ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                    ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control8(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control8));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control8(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                \r\n                                ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_Bank_Date", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControl__control10() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "hdn_Item_ID";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control11() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtBank_Date";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(90D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "input-sm hidedates datepickermmddyyy";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control11);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        public void @__DataBinding__control11(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.TextBox dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.TextBox)(sender));
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            ((System.Web.UI.IAttributeAccessor)(dataBindingExpressionBuilderTarget)).SetAttribute("value", global::System.Convert.ToString( !string.IsNullOrEmpty( Convert.ToString( Eval("Date")))?(Convert.ToDateTime(Eval("Date")).ToString("MM/dd/yyyy")):string.Empty , global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control12() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ImageUrl = "/_layouts/15/images/CBP_Images/Calender.png";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "vertical-align: top");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control9(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control10();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control11();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.Image @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control12();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control7() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control8));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control9), null);
            @__ctrl.ControlStyle.Width = new System.Web.UI.WebControls.Unit(20D, global::System.Web.UI.WebControls.UnitType.Percentage);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control14(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control14));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control14(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_Bank_Item", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control16() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(85D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.ID = "txtItemDescription";
            @__ctrl.CssClass = "input-sm";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control16);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        public void @__DataBinding__control16(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.TextBox dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.TextBox)(sender));
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString(Eval("Description") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control16();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control14));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15), null);
            @__ctrl.ControlStyle.Width = new System.Web.UI.WebControls.Unit(45D, global::System.Web.UI.WebControls.UnitType.Percentage);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control18(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control18));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control18(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_BankAdvertise", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControl__control20() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "chkAdvertisement";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control20);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        public void @__DataBinding__control20(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.CheckBox dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.CheckBox)(sender));
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Checked = ((bool)( !string.IsNullOrEmpty( Convert.ToString( Eval("Advertisement")))?(bool)Eval("Advertisement"):false ));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control19(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.CheckBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control20();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control17() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control18));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control19), null);
            @__ctrl.Visible = false;
            @__ctrl.ControlStyle.Width = new System.Web.UI.WebControls.Unit(7D, global::System.Web.UI.WebControls.UnitType.Percentage);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control22(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control22));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control22(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_Bank_Amount", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control24() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtAmount";
            @__ctrl.CssClass = "input-sm";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control24);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        public void @__DataBinding__control24(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.TextBox dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.TextBox)(sender));
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( !string.IsNullOrEmpty(Convert.ToString(Eval("Amount")))?Convert.ToDouble(Eval("Amount")).ToString("f2"):"" , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control23(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control24();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control21() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control22));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control23), null);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control6(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.TemplateField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.TemplateField @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control13();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.TemplateField @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control17();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.TemplateField @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control21();
            @__ctrl.Add(@__ctrl4);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdReimbursementItems() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdReimbursementItems = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdReimbursementItems";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.ShowHeader = true;
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.None;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            this.@__BuildControl__control6(@__ctrl.Columns);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlReimbursementItems() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlReimbursementItems = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlReimbursementItems";
            @__ctrl.CssClass = "row";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.GridView @__ctrl1;
            @__ctrl1 = this.@__BuildControlgrdReimbursementItems();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlReimbursementItemTotalInitialGrant() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlReimbursementItemTotalInitialGrant = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlReimbursementItemTotalInitialGrant";
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlReimbursementItemTotalInitialGrant));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__RenderpnlReimbursementItemTotalInitialGrant(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                <div class=\"row border-gray\">\r\n                    <table style" +
                    "=\"width: 100%\" cellpadding=\"10px\">\r\n                        <tr>\r\n              " +
                    "              <th style=\"text-align: right\">\r\n                                ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_BankNetAmountInitial", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            </th>\r\n                            <th style=\"text-" +
                    "align: left\">$ 50,000.00</th>\r\n                        </tr>\r\n                  " +
                    "  </table>\r\n                </div>\r\n            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlbtnAddReimbursementItem() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            this.btnAddReimbursementItem = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnAddReimbursementItem";
            @__ctrl.ImageUrl = "/_layouts/15/Images/CBP_Images/invite.png";
            @__ctrl.ValidationGroup = "valgroupAddReimbursementItem";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlbtnReimbursementItemError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.btnReimbursementItemError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnReimbursementItemError";
            @__ctrl.CssClass = "text-danger";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_BankTotal() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_BankTotal = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_BankTotal";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_BankDeduct() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_BankDeduct = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_BankDeduct";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_BankNetAmount() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_BankNetAmount = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_BankNetAmount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlReimbursementItemTotal() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlReimbursementItemTotal = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlReimbursementItemTotal";
            @__ctrl.Visible = false;
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            @__ctrl1 = this.@__BuildControlbtnAddReimbursementItem();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtnReimbursementItemError();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllbl_BankTotal();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControllbl_BankDeduct();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControllbl_BankNetAmount();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlReimbursementItemTotal));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__RenderpnlReimbursementItemTotal(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                <div class=\"form-group\">\r\n                    ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                    <h2 class=\"subheading text-left\" style=\"display: inline; ma" +
                    "rgin: 0;\">\r\n                        <small>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_BankAddItems", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</small>\r\n                    </h2>\r\n                    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write(@"
                </div>
                <div class=""row border-gray"">
                    <table style=""width: 100%"" cellpadding=""10px"">
                        <tr>
                            <th style=""text-align: right"">
                                ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_BankTotal", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            </th>\r\n                            <th style=\"text-" +
                    "align: left\">$\r\n                                ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                            </th>\r\n                        </tr>\r\n             " +
                    "           <tr>\r\n                            <th style=\"text-align: right\">\r\n   " +
                    "                             ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_BankDeduct", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            </th>\r\n                            <th style=\"text-" +
                    "align: left\">$\r\n                                ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                            </th>\r\n                        </tr>\r\n             " +
                    "           <tr>\r\n                            <th style=\"text-align: right\">\r\n   " +
                    "                             ");
                        @__w.Write(SPFunctions.LocalizeUI("lbl_BankNetAmount", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                            </th>\r\n                            <th style=\"text-" +
                    "align: left\">$\r\n                                ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n                            </th>\r\n                        </tr>\r\n             " +
                    "       </table>\r\n                </div>\r\n            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlReimbursementSalary() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlReimbursementSalary = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlReimbursementSalary";
            @__ctrl.Visible = false;
            @__ctrl.CssClass = "row";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTransferBankName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTransferBankName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTransferBankName";
            @__ctrl.CssClass = "input-sm";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTransferBankCode() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTransferBankCode = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTransferBankCode";
            @__ctrl.CssClass = "input-sm";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTransferBankAccount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTransferBankAccount = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTransferBankAccount";
            @__ctrl.CssClass = "input-sm";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTransferBankSwift() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTransferBankSwift = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTransferBankSwift";
            @__ctrl.CssClass = "input-sm";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTransferBankAcHolderName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTransferBankAcHolderName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTransferBankAcHolderName";
            @__ctrl.CssClass = "input-sm";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchk_RemarksInitialGrant() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            this.chk_RemarksInitialGrant = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "chk_RemarksInitialGrant";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlDirectBankTransfer() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlDirectBankTransfer = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlDirectBankTransfer";
            @__ctrl.CssClass = "row";
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtTransferBankName();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtTransferBankCode();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxtTransferBankAccount();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtTransferBankSwift();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            @__ctrl5 = this.@__BuildControltxtTransferBankAcHolderName();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.CheckBox @__ctrl6;
            @__ctrl6 = this.@__BuildControlchk_RemarksInitialGrant();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlDirectBankTransfer));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__RenderpnlDirectBankTransfer(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                <p><b>");
              @__w.Write(SPFunctions.LocalizeUI("lblHead_BankInfo", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write(@"</b></p>
                <div class=""border-gray "" style=""padding-left: 10px; padding-right: 10px;"">
                    <div class=""row"" style=""padding-bottom: 0px;"">
                        <div class=""col-md-4"">
                            <p>
                                <label>");
                               @__w.Write(SPFunctions.LocalizeUI("lbl_BankName", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                            </p>\r\n                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                        </div>\r\n                        <div class=\"col-md-4\">\r" +
                    "\n                            <p>\r\n                                <label>");
                               @__w.Write(SPFunctions.LocalizeUI("lbl_BankCode", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                            </p>\r\n                            ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                        </div>\r\n                        <div class=\"col-md-4\">\r" +
                    "\n                            <p>\r\n                                <label>");
                               @__w.Write(SPFunctions.LocalizeUI("lbl_BankAccNum", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                            </p>\r\n                            ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                        </div>\r\n                    </div>\r\n                   " +
                    " <div class=\"row\" style=\"padding-bottom: 0px;\">\r\n\r\n                        <div " +
                    "class=\"col-md-4\">\r\n                            <p>\r\n                            " +
                    "    <label>");
                               @__w.Write(SPFunctions.LocalizeUI("lbl_BankSwift", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                            </p>\r\n                            ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                        </div>\r\n                        <div class=\"col-md-4\">\r" +
                    "\n                            <p>\r\n                                <label>");
                               @__w.Write(SPFunctions.LocalizeUI("lbl_BankAccHolder", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                            </p>\r\n                            ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n                        </div>\r\n                    </div>\r\n                   " +
                    " <div class=\"row\">\r\n                        <p>\r\n                            <la" +
                    "bel>");
                           @__w.Write(SPFunctions.LocalizeUI("lbl_Remarks", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                        </p>\r\n                        <ol class=\"number" +
                    "list\" style=\"margin-top: 0px;\">\r\n                            <li>1. ");
                           @__w.Write(SPFunctions.LocalizeUI("lbl_Bank_InitGrant_Remarks1", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</li>\r\n                            <li>2. ");
                           @__w.Write(SPFunctions.LocalizeUI("lbl_Bank_InitGrant_Remarks2", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</li>\r\n                            <li>3. ");
                           @__w.Write(SPFunctions.LocalizeUI("lbl_Bank_InitGrant_Remarks3", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</li>\r\n                        </ol>\r\n                        <p>\r\n              " +
                    "              ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n                            ");
                    @__w.Write(SPFunctions.LocalizeUI("lbl_chk_Remarks", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                        </p>\r\n\r\n                    </div>\r\n                </d" +
                    "iv>\r\n            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::CBP_EMS_SP.CPIP_FA_Reimbursement_Form.VisualWebPart1.VisualWebPart1 @__ctrl) {
            global::System.Web.UI.WebControls.HiddenField @__ctrl1;
            @__ctrl1 = this.@__BuildControlhdn_FAApplicationID();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllblApplicant();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllblApplicationNo();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControllblLastSubmitted();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.RadioButtonList @__ctrl5;
            @__ctrl5 = this.@__BuildControlrdo_Categories();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.DropDownList @__ctrl6;
            @__ctrl6 = this.@__BuildControlddlCompanyList();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.Image @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control2();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.Panel @__ctrl8;
            @__ctrl8 = this.@__BuildControlpnlBankChequePayble();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.Panel @__ctrl9;
            @__ctrl9 = this.@__BuildControlpnlEventsAttend();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.Panel @__ctrl10;
            @__ctrl10 = this.@__BuildControlpnlslct_Location();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.Panel @__ctrl11;
            @__ctrl11 = this.@__BuildControlpnplEventCatBC();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.Panel @__ctrl12;
            @__ctrl12 = this.@__BuildControlpnlReimbursementItems();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.WebControls.Panel @__ctrl13;
            @__ctrl13 = this.@__BuildControlpnlReimbursementItemTotalInitialGrant();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.WebControls.Panel @__ctrl14;
            @__ctrl14 = this.@__BuildControlpnlReimbursementItemTotal();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.WebControls.Panel @__ctrl15;
            @__ctrl15 = this.@__BuildControlpnlReimbursementSalary();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.WebControls.Panel @__ctrl16;
            @__ctrl16 = this.@__BuildControlpnlDirectBankTransfer();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write(@"

<style>
    .emscontent .main {
        margin-top: 50px;
    }

    .emscontent .tr_width .col-md-1 {
        width: 12px;
    }

    .emscontent .tr_width {
        padding-left: 40px;
    }

    .word-wrap {
        overflow: hidden;
        word-break: break-all;
    }

    .label-text {
        color: black;
        word-wrap: normal;
    }
</style>

<div class=""page"">

    <!-- start-main -->
    <div class=""main"">
        <!-- -728x90- -->
        <div class=""custom-form-wd-img border-gray boxcenter width-80 pagewhiteblock"">
            <div>
                <span class=""form__head"">");
                                 @__w.Write(SPFunctions.LocalizeUI("lbl_Application_Heading_Reimbursement", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</span>\r\n            </div>\r\n            <div class=\"form__summary\">\r\n           " +
                    "     <div class=\"row\" style=\"padding: 12px 20px\">\r\n                    <div clas" +
                    "s=\"col-md-2 boldgraylbl\">");
                                              @__w.Write(SPFunctions.LocalizeUI("Application_Summary_Lbl_Applicant", "CyberportEMS_Common") );

            @__w.Write("</div>\r\n                    <div class=\"col-md-3 word-wrap\">\r\n                   " +
                    "     ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                    </div>\r\n                    <div class=\"col-md-3 boldgraylb" +
                    "l\">");
                                              @__w.Write(SPFunctions.LocalizeUI("Application_Summary_Lbl_AppNum", "CyberportEMS_Common") );

            @__w.Write("</div>\r\n                    <div class=\"col-md-4\">\r\n                        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                    </div>\r\n                </div>\r\n                <div class=" +
                    "\"row\" style=\"padding: 12px 20px\">\r\n                    <div class=\"col-md-2 bold" +
                    "graylbl\">");
                                              @__w.Write(SPFunctions.LocalizeUI("Application_Summary_Lbl_LastSubmit", "CyberportEMS_Common") );

            @__w.Write("</div>\r\n                    <div class=\"col-md-3\">\r\n                        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write(@"
                    </div>
                    <div class=""col-md-3 boldgraylbl""></div>
                    <div class=""col-md-4 boldgraylbl""></div>
                </div>
            </div>
            <div class=""form-group margin-bottom10 border-bottom"">
                <div>");
             @__w.Write(SPFunctions.LocalizeUI("lblHead_FA_Option", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</div>\r\n                ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n            <div class=\"row\">\r\n                <p>\r\n       " +
                    "             ");
            @__w.Write(SPFunctions.LocalizeUI("lblHead_FA_Company", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                </p>\r\n                <p>\r\n                    ");
            @__w.Write(SPFunctions.LocalizeUI("lbl_FA_CompanyDescription", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("\r\n                </p>\r\n            </div>\r\n            <div class=\"row\">\r\n\r\n    " +
                    "            <div class=\"col-md-4\">\r\n                    <p>\r\n                   " +
                    "     <label>");
                       @__w.Write(SPFunctions.LocalizeUI("lbl_CompanyName", "CyberportEMS_CPIP_Reimbursement") );

            @__w.Write("</label>\r\n                    </p>\r\n                    ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n                    ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n            ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n\r\n            ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n            ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<link href=\"/_layouts/15/Styles/CBP_Style" +
                    "s/jquery-ui.css\" rel=\"stylesheet\" />\r\n\r\n<script src=\"/_layouts/15/Styles/CBP_Sty" +
                    "les/jquery-ui.js\" type=\"text/javascript\"></script>\r\n<script type=\"text/javascrip" +
                    "t\">\r\n    $(\".datepickermmddyyy\").datepicker({\r\n\r\n        dateFormat: \"mm/dd/yy\"," +
                    "\r\n        // showButtonPanel: true,\r\n        // changeMonth: true,\r\n        // c" +
                    "hangeYear: true,\r\n        //changeDate: true,\r\n\r\n        //beforeShow: function " +
                    "(el, dp) {\r\n        //    $(\'.ui-datepicker-calendar\').show();\r\n        //    //" +
                    "var datestr;\r\n        //    //console.log(datestr);\r\n        //    //console.log" +
                    "($(this).val());\r\n        //    //console.log(($(this).val()).length);\r\n        " +
                    "//    //if ((datestr = $(this).val()).length > 0) {\r\n        //    //    //var d" +
                    "ate = datestr.substring(0, 2);\r\n        //    //    //console.log(date);\r\n      " +
                    "  //    //    var year = datestr.substring(datestr.length - 4, datestr.length);\r" +
                    "\n        //    //    var month = jQuery.inArray(datestr.substring(0, datestr.len" +
                    "gth - 5), $(this).datepicker(\'option\', \'monthNamesShort\'));\r\n        //    //   " +
                    " $(this).datepicker(\'option\', \'defaultDate\', new Date(year, month, 1));\r\n       " +
                    " //    //    $(this).datepicker(\'setDate\', new Date(year, month, 1));\r\n        /" +
                    "/    //}\r\n        //}\r\n        //onClose: function (dateText, inst) {\r\n\r\n       " +
                    " //    var month = $(\"#ui-datepicker-div .ui-datepicker-month :selected\").val();" +
                    "\r\n        //    var year = $(\"#ui-datepicker-div .ui-datepicker-year :selected\")" +
                    ".val();\r\n        //    $(this).datepicker(\'setDate\', new Date(year, month, 1));\r" +
                    "\n\r\n        //}\r\n    });\r\n</script>\r\n");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
