ALTER TABLE TB_APPLICATION_COMPANY_CORE_MEMBER ALTER COLUMN Name nvarchar(255) NULL
ALTER TABLE TB_APPLICATION_COMPANY_CORE_MEMBER ALTER COLUMN Position nvarchar(255) NULL
ALTER TABLE TB_APPLICATION_COMPANY_CORE_MEMBER ALTER COLUMN HKID nvarchar(255) NULL
ALTER TABLE TB_APPLICATION_CONTACT_DETAIL ALTER COLUMN Last_Name_Eng nvarchar(255) NULL
ALTER TABLE TB_APPLICATION_CONTACT_DETAIL ALTER COLUMN First_Name_Eng nvarchar(255) NULL
ALTER TABLE TB_APPLICATION_FUNDING_STATUS ALTER COLUMN Date datetime NULL
ALTER TABLE TB_APPLICATION_FUNDING_STATUS ALTER COLUMN Programme_Name nvarchar(255) NULL
ALTER TABLE TB_APPLICATION_FUNDING_STATUS ALTER COLUMN Application_Status nvarchar(255) NULL