ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD [First_Name] nvarchar(255)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD [Title] nvarchar(255)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD Address1 nvarchar(500)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD Address2 nvarchar(500)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD Address3 nvarchar(500)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD City nvarchar(255)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD Country nvarchar(255)

ALTER TABLE [TB_VETTING_MEMBER_INFO]
ADD Salutation nvarchar(10)


