ALTER TABLE TB_INCUBATION_APPLICATION
ADD Application_Parent_ID nvarchar(36)


ALTER TABLE TB_CCMF_APPLICATION
ADD Application_Parent_ID nvarchar(36)

ALTER TABLE [TB_APPLICATION_CONTACT_DETAIL]
ALTER COLUMN Contact_No nvarchar(255)

ALTER TABLE [TB_APPLICATION_CONTACT_DETAIL]
ALTER COLUMN Fax nvarchar(20)
