

/****** Object:  Table [dbo].[TB_PRESENTATION_APPLICATION_REMARKS]    Script Date: 8/31/2017 3:13:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_PRESENTATION_APPLICATION_REMARKS](
	[Vetting_Meeting_Remark_ID] [uniqueidentifier] NOT NULL,
	[Vetting_Appilcation_ID] [uniqueidentifier] NOT NULL,
	[Withdraw] [bit] NOT NULL,
	[Remark] [nvarchar](255) NOT NULL,
	[Created_By] [nvarchar](50) NOT NULL,
	[Created_Date] [datetime] NOT NULL,
	[Modified_By] [nvarchar](50) NOT NULL,
	[Modified_Date] [datetime] NULL,
 CONSTRAINT [PK_TB_PRESENTATION_APPLICATION_REMARKS] PRIMARY KEY CLUSTERED 
(
	[Vetting_Meeting_Remark_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TB_PRESENTATION_APPLICATION_REMARKS] ADD  CONSTRAINT [DF_TB_PRESENTATION_APPLICATION_REMARKS_Withdraw]  DEFAULT ((0)) FOR [Withdraw]
GO

ALTER TABLE [dbo].[TB_PRESENTATION_APPLICATION_REMARKS] ADD  CONSTRAINT [DF_TB_PRESENTATION_APPLICATION_REMARKS_Remark]  DEFAULT (N'False') FOR [Remark]
GO


